#' Mock app with one teal module (tm_t_events).
#'
#' \code{mock_mod_teal} launches a mock app with the tm_t_events teal module by means of the module manager
#' (dv.manager).
#'
#' @export
#'
mock_mod_teal <- function() {
  dm <- pharmaversesdtm::dm |>
    dplyr::mutate(
      ARM = as.factor(dplyr::if_else(ARM == "", "<EMPTY>", ARM)),
      ACTARM = as.factor(dplyr::if_else(ACTARM == "", "<EMPTY>", ACTARM)),
      ARMCD = as.factor(dplyr::if_else(ARMCD == "", "<EMPTY>", ARMCD))
    )

  ae <- pharmaversesdtm::ae

  data_list <- list(
    dm = dm,
    ae = ae
  )

  j_key <- teal.data::join_keys(
    teal.data::join_key(
      "dm",
      keys = c("STUDYID", "USUBJID")
    ),
    teal.data::join_key(
      "ae",
      keys = c("STUDYID", "USUBJID")
    ),
    teal.data::join_key(
      "dm",
      "ae",
      keys = c("STUDYID", "USUBJID")
    )
  )

  mod_events <- teal.modules.clinical::tm_t_events(
    label = "Adverse Event Table",
    dataname = "ae",
    parentname = "dm",
    arm_var = teal.transform::choices_selected(c("ARM", "ARMCD"), "ARM"),
    llt = teal.transform::choices_selected(
      choices = teal.transform::variable_choices(ae, c("AETERM", "AEDECOD")),
      selected = c("AEDECOD")
    ),
    hlt = teal.transform::choices_selected(
      choices = teal.transform::variable_choices(ae, c("AEBODSYS", "AESOC")),
      selected = "AEBODSYS"
    ),
    add_total = TRUE,
    event_type = "adverse event"
  )

  module_list <- list(
    "Events" = mod_teal(
      "events",
      mod_events,
      j_keys = j_key
    )
  )

  dv.manager::run_app(
    data = list("demo" = data_list, "demo2" = data_list),
    module_list = module_list,
    filter_data = "dm"
  )
}

#' Mock app with multiple teal modules (m_variable_browser, tm_outliers, tm_t_summary).
#'
#' \code{mock_mod_teal_multi} launches a mock app with the tm_variable_browser, tm_outliers, and tm_t_summary
#' teal modules by means of the module manager (dv.manager).
#'
#' @export
#'
mock_mod_teal_multi <- function() {

  dm <- pharmaversesdtm::dm |>
    dplyr::mutate(
      ARM = as.factor(dplyr::if_else(ARM == "", "<EMPTY>", ARM)),
      ACTARM = as.factor(dplyr::if_else(ACTARM == "", "<EMPTY>", ACTARM)),
      ARMCD = as.factor(dplyr::if_else(ARMCD == "", "<EMPTY>", ARMCD))
    )

  ae <- pharmaversesdtm::ae

  data_list <- list(
    dm = dm,
    ae = ae
  )

  data_list$dm_de <- data_list[["dm"]] |>
    dplyr::select(dplyr::all_of(c("USUBJID", "STUDYID", "AGE", "SEX", "RACE", "ETHNIC", "ARM", "ACTARM", "COUNTRY")))

  data_list2 <- list(
    dm = safetyData::sdtm_dm,
    ae = safetyData::sdtm_ae
  )
  data_list2$dm_de <- data_list2[["dm"]] |>
    dplyr::select(dplyr::all_of(c("USUBJID", "STUDYID", "AGE", "SEX", "RACE", "ETHNIC", "ARM", "ACTARM", "COUNTRY")))

  j_key <- teal.data::join_keys(
    teal.data::join_key(
      "dm",
      keys = c("STUDYID", "USUBJID")
    ),
    teal.data::join_key(
      "ae",
      keys = c("STUDYID", "USUBJID")
    ),
    teal.data::join_key(
      "dm",
      "ae",
      keys = c("STUDYID", "USUBJID")
    ),
    teal.data::join_key(
      "dm_de",
      keys = c("STUDYID", "USUBJID")
    ),
    teal.data::join_key(
      "dm",
      "dm_de",
      keys = c("STUDYID", "USUBJID")
    )
  )

  tm_var <- teal.modules.general::tm_variable_browser(
    datasets_selected = c("dm", "ae"),
    parent_dataname = "dm"
  )

  fact_vars <- names(Filter(isTRUE, sapply(data_list[["dm"]], is.factor)))
  vars <- teal.transform::choices_selected(teal.transform::variable_choices(data_list[["dm"]], fact_vars))

  tm_out <- teal.modules.general::tm_outliers(
    outlier_var = list(
      teal.transform::data_extract_spec(
        dataname = "dm",
        select = teal.transform::select_spec(
          label = "Select variable:",
          choices = teal.transform::variable_choices(data_list[["dm"]], "AGE"),
          selected = "AGE",
          multiple = FALSE,
          fixed = FALSE
        )
      )
    ),
    categorical_var = list(
      teal.transform::data_extract_spec(
        dataname = "dm",
        filter = teal.transform::filter_spec(
          vars = vars,
          choices = teal.transform::value_choices(data_list[["dm"]], vars$selected),
          selected = teal.transform::value_choices(data_list[["dm"]], vars$selected),
          multiple = TRUE
        )
      )
    ),
    ggplot2_args = list(
      teal.widgets::ggplot2_args(
        labs = list(subtitle = "Plot generated by Outliers Module")
      )
    )
  )

  tm_sum <- teal.modules.clinical::tm_t_summary(
    label = "Demographic Table",
    dataname = "dm_de",
    parentname = "dm_de",
    arm_var = teal.transform::choices_selected(c("ARM", "ARMCD"), "ARM"),
    add_total = TRUE,
    summarize_vars = teal.transform::choices_selected(
      c("AGE", "SEX", "RACE", "ETHNIC", "ARM", "ACTARM", "COUNTRY"),
      c("SEX", "RACE")
    ),
    useNA = "ifany"
  )

  module_list <- list(
    "Variable browser" = mod_teal(
      "test",
      tm_var,
      j_keys = j_key
    ),
    "Outliers" = mod_teal(
      "out",
      tm_out,
      j_keys = j_key
    ),
    "Summary" = mod_teal(
      "sum",
      tm_sum,
      j_keys = j_key
    )
  )

  dv.manager::run_app(
    data = list("demo" = data_list),
    module_list = module_list,
    filter_data = "dm"
  )

}
